server:
  undertow:
    buffer-size: 512    # Buffer más pequeño (menos memoria usada)
    direct-buffers: false
    threads:
      worker: 10 # solo 10 peticiones al tiempo
      io: 2  # Mínimo de hilos de entrada/salida (I/O)

jwt:
  secret:
    key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A
  user:
    generator: tokencode
#logs
logging:
  file:
    name: D:/Spring/ProjectoInversion/logs/inversiones.log
  level:
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.http: DEBUG
    org.springframework: DEBUG

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
  jackson:
    time-zone: America/Bogota
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#Swagger
springdoc:
  api-docs:
    enabled: true
  pathsToMatch: /cliente/**,/credito/**
  swagger-ui:
    path: /doc/swagger-ui.html
    enabled: true
  #seleccionar paquetes, clases a escanear
  packagesToscan: com.cblandon.inversiones.credito

jasypt:
  encryptor:
    password: maelito
