jwt:
  secret:
    key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A
security:
  jwt:
    user:
      generator: tokencode
spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
  jackson:
    time-zone: America/Bogota
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
springdoc:
  api-docs:
    enabled: true
  pathsToMatch: /cliente/**,/credito/**
  swagger-ui:
    path: /doc/swagger-ui.html
    enabled: true
  #seleccionar paquetes, clases a escanear
  packagesToscan: com.cblandon.inversiones.credito

jasypt:
  encryptor:
    password: maelito
