server:
    port: 8091

jwt:
    secret:
        key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A
    user:
        generator: tokencode
#logs
logging:
    file:
        name: D:/Spring/ProjectoInversion/logs/inversiones.log
    level:
        org:
            hibernate:
                SQL: DEBUG
spring:
    datasource:
        password: ENC(qR0tWIke7ESiL++MKUbIx9ZiwB+BWIgF1j6zLyEOReTfJiQPXz3YEqlGMXEW6aFK)
        url: jdbc:mysql://localhost:3306/apirest
        username: root
    #zona horaria
    jackson:
        time-zone: America/Bogota
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
#Swagger
springdoc:
    api-docs:
        # habilitar/deshabilitar api-docs/swagger
        enable: true
    pathsToMatch: /cliente/**,/credito/**
    swagger-ui:
        #definir ruta de swagger
        path: /doc/swagger-ui.html
        enabled: true
    #seleccionar paquetes, clases a escanear
    packagesToscan: com.cblandon.inversiones.credito

jasypt:
    encryptor:
        password: maelito